### ISSUE TITLE
predict vs. assign vs. pull_clustering

### ISSUE THREAD

**Issue by kbodwin** [EmilHvitfeldt/tidyclust#10]
Some clustering methods can be used to assign new observations to existing clusters.  Some cannot; and are only descriptions/structures of the observed data.

Do we want to use `predict()` when it is appropriate?

What function do we make to pull the cluster assignments on existing data from a fitted `celery` object?

**Comment by EmilHvitfeldt** [comment]
This issue is more or less dealt with. I'm closing this issue for now, any talk about how these functions should work with extraction mode should be discussed here: https://github.com/EmilHvitfeldt/tidyclust/issues/1
