### ISSUE TITLE
cluster alignment/ordering

### ISSUE THREAD

**Issue by kbodwin** [EmilHvitfeldt/tidyclust#21]
Functions to reorder cluster labels according to:

- size
- model metrics, like within SS
- post-metrics, like enrichment to external variables
- coherence with another set of cluster assignments

Reference `forcats` style factor reordering functions.

**Comment by EmilHvitfeldt** [comment]
This was closed in https://github.com/EmilHvitfeldt/tidyclust/commit/c31db8fb793bd161c5215faf8e831db9b6532161
