### ISSUE TITLE
tuning and dimension reduction

### ISSUE THREAD

**Issue by ninohardt** [EmilHvitfeldt/tidyclust#67]
Is dimension reduction pre-processing, or is it part of the clustering model itself? For instance, amazon-denseclus combines dimension reduction (UMAP) with clustering (HDBSCAN), and there are tuning parameters relating to each of them (n_neighbors for UMAP, min_samples, min_cluster_size for HDBSCAN). 

Either way, we need a tidymodels tune::tune_grid equivalent that can cover the dimension reduction and clustering component, optimizing against a set of cluster indices.

**Comment by EmilHvitfeldt** [comment]
In the tidymodels framework we consider dimension reduction to be part of the preprocessing. So for umap you would be using `embed::step_umap()`.

`tune_cluster()` should already be able to handle this 😄
