### ISSUE TITLE
add_distance?

### ISSUE THREAD

**Issue by kbodwin** [EmilHvitfeldt/tidyclust#8]
A large number of clustering methods - though not all - rely on a choice of distance or dissimilarity measure between observations.  

Perhaps this simply appears as a tuning parameter that is repeated in several model specifications.

But perhaps it's ubiquitous enough, or "core" decision enough, to be explicitly included in the model specification, much like `add_mode()`.

I'm not convinced at present that it should be separated in this way, but worth considering.

**Comment by EmilHvitfeldt** [comment]
We talked about this doing one of the meetings, and we were going to use this on a engine by engine via `set_engine()`
